### ISSUE TITLE
What is the key to access the database.

### ISSUE THREAD

**Issue by venkatBoddapati** [kelvins/US-Cities-Database#2]
Hi Kelvins,

Can you please share "Key" to access the database. As the dbfile is encrypted with a key, We can not able to access it directly.

Thanks
Venkat

**Comment by kelvins** [comment]
Hello @venkatBoddapati, 

I'm not sure what you mean by "Key". All information, states, cities, are in the SQL file, you can open it in any text editor and see its [raw content](https://raw.githubusercontent.com/kelvins/US-Cities-Database/master/us_cities.sql). You should use the SQL file to create a database. The database itself usually needs a password which is defined by you.
