### ISSUE TITLE
Add Zip Code 

### ISSUE THREAD

**Issue by MoosebuttHoggard** [kelvins/US-Cities-Database#6]
Can you please add back in the Zip Code statement for this dev obj?  That is the missing link for my data pull.

**Comment by kelvins** [comment]
Hello @MoosebuttHoggard, as I am no longer using these data, I'm not updating this project.

Anyway, feel free to fork it and make your own changes. Maybe you can find the information you need here: https://www.farinspace.com//us-cities-and-state-sql-dump/
